[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://tpss-quiz-app.vercel.app"
  GENERATE_SOURCEMAP = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200